# Generated by Django 4.2.11 on 2025-05-27 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='building',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='created_by',
           field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, default=1, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='floor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='link',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='local_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='password',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='public_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='remote_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='username',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='vlan',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
