# Generated by Django 4.2.11 on 2025-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_networkdevice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='building',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='floor',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='link',
            field=models.URLField(blank=True, default='https://example.com', null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='password',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='remote_ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='room_number',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='username',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='vlan',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
    ]
