# Generated by Django 4.2.11 on 2025-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_networkdevice_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='liked_by',
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='password',
            field=models.CharField(blank=True, default='Password here', max_length=100, null=True),
        ),
    ]
