# Generated by Django 4.2.11 on 2025-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_networkdevice_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='note',
            field=models.TextField(blank=True, default='No note', null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='password',
            field=models.CharField(blank=True, default='MySecurePassword123!', max_length=100, null=True),
        ),
    ]
